# additional ClusterRoleBinding to work with UCP/MKE
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kube-system-default:cluster-admin'
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
